### PR TITLE
Cache and add refresh command

### PR DESCRIPTION
**Pull request by jacksongoode**
This adds a refresh command so that people are able to get new changes from the repository source. I also simplified the zip extractor.

### CODE REVIEW

**Comment by jacksongoode** [comment]
@ryanccn Any comments on this? I added some git features which you may or may not want included, but it felt useful for checking the source  for changes.

**Comment by jacksongoode** [comment]
Just checking once more in case you've been busy :)

**Comment by jacksongoode** [comment]
@ryanccn Hi, just seeing if this would be possible to be merged in? I've been using it regularly and there haven't been any issues.

**Comment by ryanccn** [comment]
Couldn't users just run `nyoom switch <name>` again to update?

**Comment by ryanccn** [comment]
I don't think having a dependency on Git and using it for incremental updates makes sense, since nyoom should ideally be as independent from OS dependencies as possible (which is why the unzip functionality is in Rust!). nyoom's source scheme is modeled after Nix's [flake references](https://nix.dev/manual/nix/2.18/command-ref/new-cli/nix3-flake#flake-references), and with Nix, flakes from known Git providers such as GitHub are downloaded as archives, since

> These are downloaded as tarball archives, rather than through Git. This is often much faster and uses less disk space since it doesn't require fetching the entire history of the repository. On the other hand, it doesn't allow incremental fetching (but **full downloads are often faster than incremental fetches**!).

This is why downloading sources as archives and re-fetching them to update makes more sense IMO. I appreciate the loads of work you've put into this PR; however, I don't think I agree with its premise so I won't be able to merge it at the end of the day.

**Pull request closed without merging**
